version: "3.9"

services:
  # ---------------------------------------------------------
  # DRIVER LOCATION SERVICE
  # ---------------------------------------------------------
  driver-location:
    build:
      context: .
      dockerfile: src/driver-location-service/Dockerfile
    container_name: driver-location-service
    ports:
      - "8003:8003"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8003/docs"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - ride-net

  # ---------------------------------------------------------
  # DISPATCH SERVICE
  # ---------------------------------------------------------
  dispatch:
    build:
      context: .
      dockerfile: src/dispatch-service/Dockerfile
    container_name: dispatch-service
    ports:
      - "8002:8002"
    restart: unless-stopped
    depends_on:
      driver-location:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/docs"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - ride-net


# -----------------------------------------------------------
# DOCKER NETWORKS
# -----------------------------------------------------------
networks:
  ride-net:
    driver: bridge
