version: "3.8"

services:
  api-gateway:
    build: ./services/api-gateway
    ports:
      - "8000:8000"
    depends_on:
      - kafka

  rider-service:
    build: ./services/rider-service

  driver-service:
    build: ./services/driver-service

  matching-service:
    build: ./services/matching-service

  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"

  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
